/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jairoartist
 */
public class AgregarProducto extends javax.swing.JFrame {
    int posX, posY;
    int uno=1;
    int dos=1;
    int tres=1;
    int cuatro=1;
    DefaultTableModel modelo = new DefaultTableModel();
    public AgregarProducto() {
        //FRame invisible
        this.setUndecorated(true);
        AWTUtilities.setWindowOpaque(this, false);
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //pane tranparente
        pnAgregarP.setBackground(new Color(255,141,63,150));
               
        //Frame redondeado
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30); 
        AWTUtilities.setWindowShape(this, forma)  ; 
        
        //Añadir columnas a modelo de tabla
       modelo.addColumn("Producto");
       modelo.addColumn("Cantidad");
       
       //Añadir Filas
       modelo.addRow(new Object[] {"Coca Cola 500ml",uno});
       modelo.addRow(new Object[] {"Fanta 500ml",dos});
       modelo.addRow(new Object[] {"Pollo Frito",tres});
       modelo.addRow(new Object[] {"Carne Asada",cuatro});
       
        //Añadir modelo a tabla
       tblAñadirProductos.setModel(modelo);
       tblAñadirProductos.setRowHeight(60);
       tblAñadirProductos.setDefaultEditor(Object.class, null);
       //Cambiar fuente a cabecera de tabla
       tblAñadirProductos.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 20));
       tblAñadirProductos.getTableHeader().setBackground(new Color(53, 60, 63));
       tblAñadirProductos.getTableHeader().setForeground(Color.WHITE);
       //Tamaño de columnas
       tblAñadirProductos.getColumnModel().getColumn(0).setPreferredWidth(10);
       tblAñadirProductos.getColumnModel().getColumn(1).setPreferredWidth(5);
       DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
       modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
       tblAñadirProductos.getColumnModel().getColumn(1).setCellRenderer(modelocentrar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAgregarP = new javax.swing.JPanel();
        btnBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAñadirProductos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnAgregarP.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        pnAgregarP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnAgregarPMouseDragged(evt);
            }
        });
        pnAgregarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnAgregarPMousePressed(evt);
            }
        });
        pnAgregarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBoton.setBackground(new java.awt.Color(255, 141, 63));
        btnBoton.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        btnBoton.setText("OK");
        btnBoton.setPreferredSize(new java.awt.Dimension(120, 94));
        btnBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonActionPerformed(evt);
            }
        });
        pnAgregarP.add(btnBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 90, 90));

        tblAñadirProductos.setBackground(new java.awt.Color(117, 104, 103));
        tblAñadirProductos.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tblAñadirProductos.setForeground(new java.awt.Color(255, 255, 255));
        tblAñadirProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAñadirProductos);

        pnAgregarP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 610, 290));

        jButton1.setBackground(new java.awt.Color(255, 141, 63));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(94, 94));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnAgregarP.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 141, 63));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menos.png"))); // NOI18N
        jButton2.setMinimumSize(new java.awt.Dimension(94, 94));
        jButton2.setPreferredSize(new java.awt.Dimension(94, 94));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnAgregarP.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 141, 63));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AñadirProducto.png"))); // NOI18N
        jButton3.setText("Añadir Producto");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPreferredSize(new java.awt.Dimension(150, 94));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnAgregarP.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 90));

        getContentPane().add(pnAgregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBotonActionPerformed

    private void pnAgregarPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnAgregarPMousePressed
       posX = evt.getX();
       posY = evt.getY();
    }//GEN-LAST:event_pnAgregarPMousePressed

    private void pnAgregarPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnAgregarPMouseDragged
        int movX = evt.getXOnScreen()- posX;
        int movY = evt.getYOnScreen()- posY;
        this.setLocation(movX, movY);
    }//GEN-LAST:event_pnAgregarPMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tblAñadirProductos.isRowSelected(tblAñadirProductos.getSelectedRow())==true){
            String cuenta = String.valueOf(modelo.getValueAt(tblAñadirProductos.getSelectedRow(),1));
            int cuenta2 = Integer.parseInt(cuenta);
            cuenta2++;
            modelo.setValueAt(cuenta2, tblAñadirProductos.getSelectedRow(),1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(tblAñadirProductos.isRowSelected(tblAñadirProductos.getSelectedRow())==true){
            String cuenta = String.valueOf(modelo.getValueAt(tblAñadirProductos.getSelectedRow(),1));
            int cuenta2 = Integer.parseInt(cuenta);
            cuenta2--;
            modelo.setValueAt(cuenta2, tblAñadirProductos.getSelectedRow(),1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnAgregarP;
    private javax.swing.JTable tblAñadirProductos;
    // End of variables declaration//GEN-END:variables
}
