/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jairoartist
 */
public class frmActualizarMenu extends javax.swing.JFrame {

    
    public frmActualizarMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/logo.png")).getImage());
     
        miTabla();
     pnPane1.setBackground(new Color(213,214,210));
     pnPaneTabla.setBackground(new Color(213,214,210));
       
     
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppMenuAct = new javax.swing.JPopupMenu();
        ppItem1 = new javax.swing.JMenuItem();
        ppItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnPane1 = new javax.swing.JPanel();
        btnEntradas = new javax.swing.JButton();
        btnCarnes = new javax.swing.JButton();
        btnPescados = new javax.swing.JButton();
        btnPostres = new javax.swing.JButton();
        btnBebidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnPaneTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabla = new javax.swing.JTable();
        lblCabecera = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        ppItem1.setBackground(new java.awt.Color(53, 60, 63));
        ppItem1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        ppItem1.setForeground(new java.awt.Color(255, 141, 63));
        ppItem1.setText("Editar Producto");
        ppItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppItem1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppItem1MouseEntered(evt);
            }
        });
        ppMenuAct.add(ppItem1);

        ppItem2.setBackground(new java.awt.Color(53, 60, 63));
        ppItem2.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        ppItem2.setForeground(new java.awt.Color(255, 141, 63));
        ppItem2.setText("Borrar Producto");
        ppItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppItem2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppItem2MouseEntered(evt);
            }
        });
        ppMenuAct.add(ppItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resbar v0.1 Administrar Menú");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(new java.awt.Color(117, 104, 103));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(43, 49, 50));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 141, 63));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuevo.png"))); // NOI18N
        jButton1.setText("Añadir");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(327, 583, 170, 83);

        jButton3.setBackground(new java.awt.Color(42, 49, 50));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 141, 63));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        jButton3.setText("OK");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(848, 580, 140, 83);

        pnPane1.setBackground(new java.awt.Color(255, 255, 255));
        pnPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        btnEntradas.setBackground(new java.awt.Color(53, 60, 63));
        btnEntradas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnEntradas.setForeground(new java.awt.Color(255, 141, 63));
        btnEntradas.setText("Entradas");
        btnEntradas.setBorder(null);
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });

        btnCarnes.setBackground(new java.awt.Color(53, 60, 63));
        btnCarnes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCarnes.setForeground(new java.awt.Color(255, 141, 63));
        btnCarnes.setText("Carnes");
        btnCarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarnesActionPerformed(evt);
            }
        });

        btnPescados.setBackground(new java.awt.Color(53, 60, 63));
        btnPescados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPescados.setForeground(new java.awt.Color(255, 141, 63));
        btnPescados.setText("Pescados");
        btnPescados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPescadosActionPerformed(evt);
            }
        });

        btnPostres.setBackground(new java.awt.Color(53, 60, 63));
        btnPostres.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPostres.setForeground(new java.awt.Color(255, 141, 63));
        btnPostres.setText("Postres");
        btnPostres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostresActionPerformed(evt);
            }
        });

        btnBebidas.setBackground(new java.awt.Color(53, 60, 63));
        btnBebidas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBebidas.setForeground(new java.awt.Color(255, 141, 63));
        btnBebidas.setText("Bebidas");
        btnBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBebidasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Free Chancery", 1, 32)); // NOI18N
        jLabel1.setText("Categoría:");

        javax.swing.GroupLayout pnPane1Layout = new javax.swing.GroupLayout(pnPane1);
        pnPane1.setLayout(pnPane1Layout);
        pnPane1Layout.setHorizontalGroup(
            pnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPescados, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(btnPostres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
        );
        pnPane1Layout.setVerticalGroup(
            pnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPescados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPostres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pnPane1);
        pnPane1.setBounds(30, 140, 290, 420);

        pnPaneTabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));

        tbTabla.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbTablaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbTablaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabla);

        lblCabecera.setFont(new java.awt.Font("Forte", 0, 28)); // NOI18N
        lblCabecera.setText("Entradas");

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTextField1.setText("Buscar Entradas...");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton2.setBackground(new java.awt.Color(117, 104, 103));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPaneTablaLayout = new javax.swing.GroupLayout(pnPaneTabla);
        pnPaneTabla.setLayout(pnPaneTablaLayout);
        pnPaneTablaLayout.setHorizontalGroup(
            pnPaneTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPaneTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPaneTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnPaneTablaLayout.createSequentialGroup()
                        .addComponent(lblCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnPaneTablaLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnPaneTablaLayout.setVerticalGroup(
            pnPaneTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPaneTablaLayout.createSequentialGroup()
                .addComponent(lblCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPaneTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPaneTablaLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPaneTablaLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(pnPaneTabla);
        pnPaneTabla.setBounds(330, 140, 660, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_116x116.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(893, 10, 97, 110);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Forte", 1, 40)); // NOI18N
        jLabel5.setText("Administrar Menú");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 30, 520, 60);

        jLabel3.setFont(new java.awt.Font("Forte", 0, 60)); // NOI18N
        jLabel3.setText("Resbar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(720, 10, 171, 82);

        jLabel4.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel4.setText("Restaurante & Bar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(710, 70, 184, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaMouseClicked
       if ((evt.getModifiers() & 4) !=0){
         ppMenuAct.setVisible(false);        
         }else{
        ppMenuAct.setVisible(true);
        ppMenuAct.setLocation(evt.getLocationOnScreen());
         }
    }//GEN-LAST:event_tbTablaMouseClicked

    private void tbTablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaMouseEntered
      
    }//GEN-LAST:event_tbTablaMouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
         ppMenuAct.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void ppItem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppItem1MouseEntered
        ppItem1.setBackground(new Color(213,214,210));
         ppItem1.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_ppItem1MouseEntered

    private void tbTablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaMouseExited
      
    }//GEN-LAST:event_tbTablaMouseExited

    private void ppItem1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppItem1MouseExited
          ppItem1.setBackground(new Color(53,60,63));
         ppItem1.setForeground(new Color(255,141,63));
    }//GEN-LAST:event_ppItem1MouseExited

    private void ppItem2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppItem2MouseEntered
        ppItem2.setBackground(new Color(213,214,210));
         ppItem2.setForeground(Color.BLACK);
    }//GEN-LAST:event_ppItem2MouseEntered

    private void ppItem2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppItem2MouseExited
         ppItem2.setBackground(new Color(53,60,63));
         ppItem2.setForeground(new Color(255,141,63));
    }//GEN-LAST:event_ppItem2MouseExited

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
       lblCabecera.setText("Entradas");
    }//GEN-LAST:event_btnEntradasActionPerformed

    private void btnCarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarnesActionPerformed
        lblCabecera.setText("Carnes");
    }//GEN-LAST:event_btnCarnesActionPerformed

    private void btnPescadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPescadosActionPerformed
        lblCabecera.setText("Pescados");
    }//GEN-LAST:event_btnPescadosActionPerformed

    private void btnPostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostresActionPerformed
        lblCabecera.setText("Postres");
    }//GEN-LAST:event_btnPostresActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
       lblCabecera.setText("Bebidas");
    }//GEN-LAST:event_btnBebidasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       frmDashboard board = new frmDashboard();
       board.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmAgregarProductos agregar = new frmAgregarProductos();
        agregar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActualizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmActualizarMenu().setVisible(true);
            }
        });
    }
    private void miTabla(){
     //Modelo de mi tabla
     DefaultTableModel modelo = new DefaultTableModel();
     //Agregar columnas
     modelo.addColumn("Producto");
     modelo.addColumn("Precio");
      //Añadir Filas
       modelo.addRow(new Object[] {"Pollo Frito","$3.00"});
       modelo.addRow(new Object[] {"Pollo Empanisado","$2.50"});
       modelo.addRow(new Object[] {"Pollo Guisado","$3.00"});
       modelo.addRow(new Object[] {"Carne Asada","$2.00"});
       modelo.addRow(new Object[] {"Carne Guisada","$2.00"});
       modelo.addRow(new Object[] {"Pescado Frito","$4.00"});
       modelo.addRow(new Object[] {"Sopa de Gallina India","$1.75"});
       modelo.addRow(new Object[] {"Sopa de Res","$1.75"});
       modelo.addRow(new Object[] {"Sopa de Patas","$2.00"});
       //Añadir modelo a tabla, alto de fila y no editable
       tbTabla.setModel(modelo);
       tbTabla.setRowHeight(60);
       tbTabla.setDefaultEditor(Object.class, null);
       //Cambiar fuente a cabecera de tabla
       tbTabla.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 20));
       tbTabla.getTableHeader().setBackground(new Color(53, 60, 63));
       tbTabla.getTableHeader().setForeground(Color.WHITE);
       //Tamaño de columnas
       tbTabla.getColumnModel().getColumn(0).setPreferredWidth(150);
       tbTabla.getColumnModel().getColumn(1).setPreferredWidth(10);
       //Centrar texto de columnas
        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
        tbTabla.getColumnModel().getColumn(1).setCellRenderer(modelocentrar);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnCarnes;
    private javax.swing.JButton btnEntradas;
    private javax.swing.JButton btnPescados;
    private javax.swing.JButton btnPostres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCabecera;
    private javax.swing.JPanel pnPane1;
    private javax.swing.JPanel pnPaneTabla;
    private javax.swing.JMenuItem ppItem1;
    private javax.swing.JMenuItem ppItem2;
    private javax.swing.JPopupMenu ppMenuAct;
    private javax.swing.JTable tbTabla;
    // End of variables declaration//GEN-END:variables
}
