/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Frank
 */
public class frmDetalleOrden extends javax.swing.JFrame {

    /**
     * Creates new form frmDetalleOrden
     */
    public frmDetalleOrden() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //fecha del sistema
        this.txtFecha.setText(FechaSistema());
        
        //hora del sistema
        Timer tiempo= new Timer(100,new frmDetalleOrden.horas());
        tiempo.start();
        
        this.TamañoPosicionCeldas();
        
       // this.BotonesInvisibles();

        
    }

    public static String FechaSistema(){
       Date fecha= new Date();
       SimpleDateFormat formatoFecha=new SimpleDateFormat("dd/MM/YYYY");
       return formatoFecha.format(fecha);
    }
    
    class horas implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            Date HoraSis = new Date();
            String AmPm="hh:mm:ss a";
            SimpleDateFormat format=new SimpleDateFormat(AmPm);
            Calendar hoy=Calendar.getInstance();
            txtHora.setText(String.format(format.format(HoraSis),hoy));
            
         }
        
    }
    
    
    public void TamañoPosicionCeldas(){
        tblDetalleOrden.getColumnModel().getColumn(0).setPreferredWidth(240);
        tblDetalleOrden.getColumnModel().getColumn(1).setPreferredWidth(5);
        
       DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
       tcr.setHorizontalAlignment(SwingConstants.CENTER);
       tblDetalleOrden.getColumnModel().getColumn(1).setCellRenderer(tcr);
}
    public void BotonesInvisibles(){
        int fila = tblDetalleOrden.getSelectedRow();
        
        if (fila>=0){
            this.btnMas.setVisible(true);
            this.btnMenos.setVisible(true);
        }else{
            this.btnMas.setVisible(false);
            this.btnMenos.setVisible(false);
        }
            
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPrincipal = new javax.swing.JPanel();
        jpnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnlHoraFecha = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jpnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleOrden = new javax.swing.JTable();
        jpnlBotones1 = new javax.swing.JPanel();
        jpnlBotonesCantidad = new javax.swing.JPanel();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        jLabelCantidad = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jpnlPrincipal.setBackground(new java.awt.Color(212, 175, 55));
        jpnlPrincipal.setMaximumSize(new java.awt.Dimension(1024, 768));
        jpnlPrincipal.setMinimumSize(new java.awt.Dimension(1024, 768));
        jpnlPrincipal.setLayout(null);

        jpnlTitulo.setBackground(new java.awt.Color(212, 175, 55));
        jpnlTitulo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Detalle de Orden");
        jpnlTitulo.add(jLabel1);
        jLabel1.setBounds(290, 10, 390, 80);

        jpnlPrincipal.add(jpnlTitulo);
        jpnlTitulo.setBounds(37, 20, 970, 90);

        jpnlHoraFecha.setBackground(new java.awt.Color(212, 175, 55));
        jpnlHoraFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnlHoraFecha.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Fecha:");
        jpnlHoraFecha.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Hora:");
        jpnlHoraFecha.add(jLabel3);
        jLabel3.setBounds(400, 15, 62, 30);

        txtFecha.setBackground(new java.awt.Color(212, 175, 55));
        txtFecha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtFecha.setBorder(null);
        jpnlHoraFecha.add(txtFecha);
        txtFecha.setBounds(90, 20, 200, 20);

        txtHora.setBackground(new java.awt.Color(212, 175, 55));
        txtHora.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtHora.setBorder(null);
        jpnlHoraFecha.add(txtHora);
        txtHora.setBounds(470, 20, 200, 20);

        jpnlPrincipal.add(jpnlHoraFecha);
        jpnlHoraFecha.setBounds(30, 170, 750, 50);

        jpnlTabla.setBackground(new java.awt.Color(212, 175, 55));
        jpnlTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnlTabla.setLayout(null);

        tblDetalleOrden.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tblDetalleOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDetalleOrden.setRowHeight(40);
        tblDetalleOrden.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblDetalleOrden);

        jpnlTabla.add(jScrollPane1);
        jScrollPane1.setBounds(11, 12, 730, 430);

        jpnlPrincipal.add(jpnlTabla);
        jpnlTabla.setBounds(30, 250, 750, 460);

        jpnlBotones1.setBackground(new java.awt.Color(212, 175, 55));
        jpnlBotones1.setLayout(null);
        jpnlPrincipal.add(jpnlBotones1);
        jpnlBotones1.setBounds(30, 420, 390, 50);

        jpnlBotonesCantidad.setBackground(new java.awt.Color(212, 175, 55));
        jpnlBotonesCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnlBotonesCantidad.setLayout(null);

        btnMas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMas.setText("+");
        jpnlBotonesCantidad.add(btnMas);
        btnMas.setBounds(130, 10, 50, 56);

        btnMenos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnMenos.setText("-");
        jpnlBotonesCantidad.add(btnMenos);
        btnMenos.setBounds(10, 10, 50, 56);

        jLabelCantidad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelCantidad.setText("1");
        jLabelCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnlBotonesCantidad.add(jLabelCantidad);
        jLabelCantidad.setBounds(70, 10, 50, 56);

        jpnlPrincipal.add(jpnlBotonesCantidad);
        jpnlBotonesCantidad.setBounds(800, 250, 190, 80);

        btnRegresar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        jpnlPrincipal.add(btnRegresar);
        btnRegresar.setBounds(840, 580, 130, 60);

        btnOk.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnOk.setText("Ok");
        jpnlPrincipal.add(btnOk);
        btnOk.setBounds(840, 440, 130, 60);

        getContentPane().add(jpnlPrincipal);
        jpnlPrincipal.setBounds(0, 0, 1050, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetalleOrden().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnlBotones1;
    private javax.swing.JPanel jpnlBotonesCantidad;
    private javax.swing.JPanel jpnlHoraFecha;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JPanel jpnlTabla;
    private javax.swing.JPanel jpnlTitulo;
    private javax.swing.JTable tblDetalleOrden;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
